stock:
  products:
    - name: "Apples"
      price: 1.0
      discount: 10.0
      unit: BAG
    - name: "Soup"
      price: 0.65
      discount: 0.0
      unit: TIN
    - name: "Bread"
      price: 0.80
      discount: 0.0
      unit: LOAF
    - name: "Milk"
      price: 1.30
      discount: 0.0
      unit: BOTTLE